services:
  - type: web
    name: dsa-tracker
    env: node
    root: .
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
